gains:
  left_shoulder_pitch_joint: {stiffness: 50.0, damping: 3.0}
  left_shoulder_roll_joint: {stiffness: 50.0, damping: 3.0}
  left_shoulder_yaw_joint: {stiffness: 50.0, damping: 3.0}
  left_elbow_joint: {stiffness: 50.0, damping: 3.0}
  left_wrist_yaw_joint: {stiffness: 20.0, damping: 2.0}
  left_wrist_pitch_joint: {stiffness: 20.0, damping: 2.0}
  left_wrist_roll_joint: {stiffness: 20.0, damping: 2.0}
  right_shoulder_pitch_joint: {stiffness: 50.0, damping: 3.0}
  right_shoulder_roll_joint: {stiffness: 50.0, damping: 3.0}
  right_shoulder_yaw_joint: {stiffness: 50.0, damping: 3.0}
  right_elbow_joint: {stiffness: 50.0, damping: 3.0}
  right_wrist_yaw_joint: {stiffness: 20.0, damping: 2.0}
  right_wrist_pitch_joint: {stiffness: 20.0, damping: 2.0}
  right_wrist_roll_joint: {stiffness: 20.0, damping: 2.0}
